spring:
  profiles:
    active: local # 사용할 환경 설정
  
  datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 284823
    
  #datasource:
    #jdbcUrl : jdbc:mysql://localhost:3307/mysql
    #driver-class-name : com.mysql.cj.jdbc.Driver
    #username: root
    #password: 284823
  #datasource:
    #jdbcUrl: jdbc:mariadb://localhost:3306/maria
    #driver-class-name: org.mariadb.jdbc.Driver
    #username: root
    #password: 284823
       
  mvc:
    view: 
      prefix: /WEB-INF/views
      suffix: .jsp
    static-path-pattern: /static/** #spring mvc 정적경로 변경  
    
  devtools:
    livereload: # 서버 자동 재가동: JSP수정시 서버 재시작없이 바로 적용될 수 있게 설정
      enabled: true
  freemarker: 
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB 
      max-request-size: 10MB
      
  mail:
      host: smtp.gmail.com #SMTP 서버 호스트
      port: 587 #SMTP 서버 포트 
      username: ceoosm # SMTP 서버 로그인 아이디: 발신자 (ceoosm@gmail.com)
      password: syyj qhda wsgv gqdr # 앱 비밀번호는 구글 계정, 16자리 자동 설정 됨 
      properties:
        mail:
          smtp:
            auth: true #사용자 인증 시도 여부
            timeout : 5000 #Socekt Reaad Time out 
            starttls:
              enable: true
              
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false


  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 55968493342-8nhocekuh1l9qj8fq4ek7363obpugd7f.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: 
             - profile
             - email
  



#오류 : this key is used in a map and contains special characters. it is recommended to escape it by surrounding it with '[]    
logging:
  level:
    root: INFO  #INFO, WARN, ERROR, FATAL 모두 표시 -> 하위 패키지 상속
    '[com.shoppingmall.login]': DEBUG #특정 패키지 경로
    '[com.shoppingmall.post]': DEBUG
    '[com.shoppingmall.secuser]': DEBUG
    '[com.shoppingmall.jwt]': DEBUG
    '[com.shoppingmall.toaf.intercept]': debug
 
#서버 포트
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    path: /error
    whitelabel:
      enabled: false

        #카카오 페이 설정
kakaopay:
  admin-key: InwtSk8M6VlunphqPxcEZD33qYlKyYvM

mybatis:
  configuration:
    #map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
    
  type-aliases-package: com.shoppingmall.member.model
  mapper-locations: 
   - classpath:/sqlmap/**/*SQL.xml

file: 
  upload-dir: C:/Users/USER/Desktop/osm/file_upload

# secret-key는 512bit 이상을 사용해야 한다. + 유효시간: 24h(86400)
jwt:
  secret-key: Y2hvcHBhLWRvbnQtYml0ZS1tZS1zcHJpbmctYm9vdC1qd3QtdGVzdC1zZWNyZXQta2V5LWNob3BwYS1kb250LWJpdGUtbWUtc3ByaW5nLWJvb3Qtand0LXRlc3Qtc2VjcmV0LWtleQo=
  token-validity-in-sconds: 86400



            

 
