
spring:
  profiles:
    active: local # 사용할 환경 설정
  
  datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 284823
    
  #datasource:
    #jdbcUrl : jdbc:mysql://localhost:3307/mysql
    #driver-class-name : com.mysql.cj.jdbc.Driver
    #username: root
    #password: 284823
  #datasource:
    #jdbcUrl: jdbc:mariadb://localhost:3306/maria
    #driver-class-name: org.mariadb.jdbc.Driver
    #username: root
    #password: 284823
    
    
     
  mvc:
    view: 
      prefix: /WEB-INF/views
      suffix: .jsp
      
  devtools:
    livereload: # 서버 자동 재가동: JSP수정시 서버 재시작없이 바로 적용될 수 있게 설정
      enabled: true
  freemarker: 
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB 
      max-request-size: 2MB
      
  mail:
      host: smtp.gmail.com
      port: 587
      username: ceoosm
      password:        # 앱 비밀번호는 구글 계정, 16자리 설정 
      properties:
        mail:
          smtp:
            auth: true
            timeout : 5000
            starttls:
              enable: true

#오류 : this key is used in a map and contains special characters. it is recommended to escape it by surrounding it with '[]    
logging:
  level:
    root: INFO  #INFO, WARN, ERROR, FATAL 모두 표시 -> 하위 패키지 상속
    '[com.shoppingmall.login]': DEBUG #특정 패키지 경로
    '[com.shoppingmall.post]': DEBUG
    '[com.shoppingmall.toaf.intercept]': debug
 
#서버 포트
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    path: /error
    whitelabel:
      enabled: false
    
mybatis:
  configuration:
    #map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
    
  type-aliases-package: com.shoppingmall.member.model
  mapper-locations: 
   - classpath:/sqlmap/**/*SQL.xml

file: 
  upload-dir: C:/Users/USER/Desktop/osm/file_upload


# application.properties


            

 
